- hosts: localhost
  become: yes
  tasks:
    - name: Task -1 Connect to cluster
      shell: gcloud container clusters get-credentials private-cluster --zone us-east4-b --project mahmoud-ibrahim-2023

    - name: Task -2 Create Jenkins namespace
      shell: kubectl create namespace jenkins

    - name: Task -3 Deploying jenkins & loadbalancer servies
      command: kubectl apply -f /home/mahmoud/ans-file/jenkins/